language: node_js
node_js: 8

install:
  - npm ci

script:
  - npm run build
  - npm test -- --coverage

after_success:
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
